/**
 * HERMES — WikiLint.gs
 * Self-healing wiki health scan (Karpathy-style lint pass).
 */

var GMAIL_SOURCE_PATTERN = /\[source\]\(https:\/\/mail\.google\.com\/mail\/u\/0\/#inbox\/[^)]+\)/;

/**
 * CHRONOS: weekly wiki lint. Writes wiki/lint-report.md.
 */
function runWikiLint_() {
  var issues = [];
  var ts = new Date().toISOString();

  try {
    var indexContent = readWikiFile_('index.md') || '';
    if (!indexContent.trim()) {
      issues.push('index.md missing or empty');
    }

    var indexPeople = [];
    var linkRe = /\[\[people\/([^\]]+)\]\]/g;
    var m;
    while ((m = linkRe.exec(indexContent)) !== null) {
      indexPeople.push(m[1]);
    }

    var wikiFolder = getWikiFolder_();
    var drivePeople = [];
    if (wikiFolder) {
      var pf = wikiFolder.getFoldersByName('people');
      if (pf.hasNext()) {
        var peopleFolder = pf.next();
        var it = peopleFolder.getFiles();
        while (it.hasNext()) {
          var f = it.next();
          var n = f.getName();
          if (/\.md$/i.test(n)) drivePeople.push(n);
        }
      }
    } else {
      issues.push('wiki folder not found');
    }

    var indexSet = {};
    for (var i = 0; i < indexPeople.length; i++) indexSet[indexPeople[i]] = true;
    var driveSet = {};
    for (var j = 0; j < drivePeople.length; j++) driveSet[drivePeople[j]] = true;

    for (var a = 0; a < indexPeople.length; a++) {
      if (!driveSet[indexPeople[a]]) {
        issues.push('Index lists people/' + indexPeople[a] + ' but file missing in Drive');
      }
    }
    for (var b = 0; b < drivePeople.length; b++) {
      if (!indexSet[drivePeople[b]]) {
        issues.push('people/' + drivePeople[b] + ' exists in Drive but not linked from index.md');
      }
    }

    var commitmentsMd = readWikiFile_('commitments.md') || '';
    lintCommitmentsForSources_(commitmentsMd, issues);
    lintCommitmentsStale_(commitmentsMd, issues);
  } catch (e) {
    issues.push('Lint fatal: ' + e.message);
  }

  var report = [
    '# Hermes Wiki Lint Report',
    '*Run: ' + ts + '*',
    '',
    issues.length ? '## Issues (' + issues.length + ')' : '## Issues (0)',
    ''
  ];
  if (issues.length === 0) {
    report.push('*(no issues detected)*');
  } else {
    for (var k = 0; k < issues.length; k++) {
      report.push('- ' + issues[k]);
    }
  }
  report.push('');
  report.push('---');
  report.push('*Auto-generated by runWikiLint_*');

  try {
    writeWikiFile_('lint-report.md', report.join('\n'));
  } catch (e2) {
    Logger.log('[ERROR] runWikiLint_ could not write lint-report: ' + e2.message);
  }

  Logger.log('[LINT] runWikiLint_ done, issues=' + issues.length);
}

/**
 * Open checklist items under Outbound/Inbound without [source](gmail...) link.
 */
function lintCommitmentsForSources_(md, issues) {
  if (!md) return;
  var sections = [
    '## Outbound (you owe others)',
    '## Inbound (others owe you)'
  ];
  for (var s = 0; s < sections.length; s++) {
    var blocks = extractCommitmentBlocksInSection_(md, sections[s].replace('## ', ''));
    for (var i = 0; i < blocks.length; i++) {
      var firstLine = blocks[i].split('\n')[0];
      if (firstLine.indexOf('- [ ]') !== 0) continue;
      if (!GMAIL_SOURCE_PATTERN.test(firstLine)) {
        issues.push('commitments.md: open item missing Gmail source link — ' + truncate(firstLine, 120));
      }
    }
  }
}

/**
 * Open items with due date or extracted date older than 30 days, not in stale section.
 */
function lintCommitmentsStale_(md, issues) {
  if (!md) return;
  var cutoff = new Date(Date.now() - 30 * 24 * 3600000);
  var sections = [
    { title: 'Outbound (you owe others)', name: 'outbound' },
    { title: 'Inbound (others owe you)', name: 'inbound' }
  ];
  for (var s = 0; s < sections.length; s++) {
    var blocks = extractCommitmentBlocksInSection_(md, sections[s].title);
    for (var i = 0; i < blocks.length; i++) {
      var block = blocks[i];
      var first = block.split('\n')[0];
      if (first.indexOf('- [ ]') !== 0) continue;
      if (first.indexOf('~~') >= 0) continue;
      var dm = block.match(/(\d{4}-\d{2}-\d{2})/g);
      if (!dm || !dm.length) continue;
      var oldest = null;
      for (var d = 0; d < dm.length; d++) {
        var dt = new Date(dm[d]);
        if (!oldest || dt < oldest) oldest = dt;
      }
      if (oldest && oldest < cutoff) {
        issues.push('commitments.md: item possibly stale (>30d by date in line) not in Stale section — ' + truncate(first, 100));
      }
    }
  }
}

/**
 * Section heading without ## prefix for parseCommitmentSection_ style.
 */
function extractCommitmentBlocksInSection_(md, sectionHeading) {
  var start = md.indexOf('## ' + sectionHeading);
  if (start === -1) return [];
  var after = md.substring(start + sectionHeading.length + 3);
  var end = after.indexOf('\n## ');
  var section = end > 0 ? after.substring(0, end) : after;
  var lines = section.split('\n');
  var blocks = [];
  var cur = null;
  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];
    if (/^- \[ \]/.test(line)) {
      if (cur) blocks.push(cur);
      cur = line;
    } else if (cur && /^\s+>/.test(line)) {
      cur += '\n' + line;
    }
  }
  if (cur) blocks.push(cur);
  return blocks;
}
